<?php

use CodeIgniter\Router\RouteCollection;

/**
 * @var RouteCollection $routes
 */
//student
$routes->post('validateUser','Home::validateUser');
$routes->post('register','Home::register');
$routes->post('new-password','Home::newPassword');
$routes->get('logout','Home::logout');
$routes->post('upload-file','Home::uploadFile');
$routes->post('remove-file','Home::removeFile');
//ajax
$routes->post('save-profile','Home::saveProfile');
$routes->post('generate-qr-code','Cadet::qrCode');
$routes->post('cadet/items/send','Cadet::sendItems');
$routes->post('cadet/items/cancel','Cadet::cancelItems');
$routes->post('password/change','Cadet::changePassword');
$routes->get('send-email','Notification::sendEmail');

$routes->group('',['filter'=>'AlreadyLoggedIn'],function($routes)
{
    $routes->get('/', 'Home::index');
    $routes->get('sign-up','Home::signUp');
    $routes->get('forgot-password', 'Home::forgotPassword');
    $routes->get('success/(:any)','Home::successLink/$1');
    $routes->get('resend/(:any)','Home::resend/$1');
    $routes->get('activate/(:any)','Home::activateAccount/$1');
});

$routes->group('',['filter'=>'AuthCheck'],function($routes)
{
    $routes->get('cadet/dashboard','Home::studentDashboard');
    $routes->get('cadet/items','Home::allItems');
    $routes->get('cadet/items/borrow','Home::borrowItem');
    $routes->get('cadet/profile','Home::studentProfile');
    $routes->get('cadet/qr-code','Home::qrCode');
    $routes->get('cadet/upload','Home::upload');
    $routes->get('cadet/trainings','Home::studentTrainings');
    $routes->get('cadet/trainings/view/(:any)','Home::viewTraining/$1');
    $routes->get('cadet/attendance','Home::studentAttendance');
    $routes->get('cadet/performance','Home::studentPerformance');
    $routes->get('cadet/account-security','Home::accountSecurity');
});

//admin
$routes->post('checkAuth','Administrator::checkAuth');
$routes->get('sign-out','Administrator::logout');
$routes->get('download','Download::downloadFile');
$routes->post('restore','Restore::restoreFile');
//cadet
$routes->get('registered','Administrator::registeredUser');
$routes->get('enrolled','Administrator::enrolledCadet');
$routes->post('edit-cadet','Administrator::modifyCadet');
$routes->post('enroll-cadet','Administrator::enrollCadet');
//Plans
$routes->get('plans/fetch','Administrator::fetchPlans');
$routes->post('plans/store','Administrator::storePlans');
$routes->post('plans/update','Administrator::updatePlans');
$routes->get('assignment','Administrator::assignment');
$routes->post('assignment/save','Administrator::saveAssignment');
$routes->post('assignment/remove','Administrator::removeAssignment');
//batch
$routes->post('gradebook/batch/save','Administrator::saveBatch');
$routes->post('gradebook/batch/update','Administrator::updateBatch');
$routes->post('gradebook/grades/save',to: 'Enrolment::saveGrades');
//attendance
$routes->get('gradebook/batch/list','Enrolment::fetchList');
$routes->get('attendance/generate','Enrolment::generateAttendance');
// $routes->post('gradebook/class/save','Enrolment::saveClass');
$routes->get('gradebook/class/fetch','Enrolment::fetchClass');
$routes->get('gradebook/subject/class/fetch','Enrolment::fetchSubjectClass');
$routes->get('gradebook/attendance/list','Enrolment::listAttendance');
$routes->post('gradebook/attendance/save','Enrolment::saveCompany');
//report
$routes->get('report/grades','Enrolment::fetchGrades');
$routes->post('report/grades/update','Enrolment::updateGrades');
$routes->post('report/save','Enrolment::saveReport');
$routes->get('report/view','Enrolment::viewReport');
$routes->post('report/update','Enrolment::updateReport');
$routes->post('report/modify','Enrolment::modifyReport');
//inventory
$routes->post('inventory/category/add','Inventory::addCategory');
$routes->post('inventory/category/edit','Inventory::editCategory');
$routes->get('inventory/category/fetch','Inventory::fetchCategory');
$routes->post('inventory/item/save','Inventory::saveItem');
$routes->post('inventory/item/edit','Inventory::editItem');
$routes->post('inventory/item/damage','Inventory::damageItem');
$routes->post('inventory/item/restore','Inventory::restoreItem');
$routes->post('inventory/item/borrow','Inventory::borrowItem');
$routes->post('inventory/item/return','Inventory::returnItem');
$routes->post('inventory/item/release','Inventory::releaseItem');
$routes->post('inventory/item/accept','Inventory::AcceptRequest');
$routes->post('inventory/item/decline','Inventory::declineRequest');
$routes->post('inventory/return/accept','Inventory::acceptReturn');
$routes->post('inventory/archive','Inventory::archive');
$routes->post('inventory/restore','Inventory::restore');
$routes->post('inventory/condemn','Inventory::condemn');
$routes->post('inventory/stock/add','Inventory::addStock');
//excel scanner
$routes->post('file/upload','ExcelScanner::upload');
$routes->post('grades/file/upload','Enrolment::uploadFile');
//cadet trainings
$routes->get('trainings/fetch','Enrolment::fetchTraining');
$routes->post('trainings/save','Enrolment::saveTraining');
//attendance
$routes->post('save-attendance','Administrator::saveAttendance');
//announcement
$routes->post('save-announcement','Administrator::saveAnnouncement');
$routes->post('edit-announcement','Administrator::modifyAnnouncement');
//maintenance
$routes->get('fetch-account','Administrator::fetchAccount');
$routes->post('save-account','Administrator::saveAccount');
$routes->post('edit-account','Administrator::modifyAccount');
$routes->get('fetch-permission','Administrator::fetchPermission');
$routes->post('save-permission','Administrator::savePermission');
$routes->post('edit-permission','Administrator::modifyPermission');
//my account
$routes->post('account/password/change','Administrator::changePassword');

$routes->group('',['filter'=>'AdminCheck'],function($routes)
{
    $routes->get('dashboard','Administrator::index');
    $routes->get('scanner','Home::scanner');
    //cadets
    $routes->get('cadets','Administrator::cadetInformation');
    $routes->get('cadets/edit/(:any)','Administrator::editCadet/$1');
    $routes->get('cadets/info/(:any)','Administrator::cadetInfo/$1');
    $routes->get('cadets/performance/(:any)','Administrator::cadetPerformance/$1');
    //schedules
    $routes->get('schedules','Administrator::trainingSchedule');
    $routes->get('schedules/create','Administrator::createSchedule');
    $routes->get('schedules/edit/(:any)','Administrator::editSchedule/$1');
    $routes->get('schedules/manage','Administrator::manageSchedule');
    //attendance
    $routes->get('attendance','Administrator::attendance');
    $routes->get('attendance/add','Administrator::addAttendance');
    $routes->get('attendance/view/(:any)','Administrator::viewAttendance/$1');
    //grades
    $routes->get('gradebook','Administrator::gradingSystem');
    $routes->get('gradebook/grades/add/(:any)','Administrator::addGrades/$1');
    $routes->get('gradebook/view/(:any)','Administrator::viewGradeBook/$1');
    $routes->get('gradebook/download/(:any)','Export::downloadGrades/$1');
    //subjects
    $routes->get('gradebook/subject','Administrator::allSubject');
    $routes->get('gradebook/subject/create','Administrator::createSubject');
    $routes->get('gradebook/subject/edit/(:any)','Administrator::editSubject/$1');
    $routes->get('gradebook/subject/fetch','Administrator::fetchSubject');
    $routes->get('gradebook/subject/view/(:any)','Administrator::viewSummary/$1');
    $routes->get('gradebook/subject/upload/(:any)','Administrator::uploadGrades/$1');
    //batches
    $routes->get('gradebook/batch','Administrator::allBatch');
    $routes->get('gradebook/batch/create','Administrator::createBatch');
    $routes->get('gradebook/batch/edit/(:any)','Administrator::editBatch/$1');
    $routes->get('gradebook/batch/upload/(:any)','Administrator::uploadBatch/$1');
    $routes->get('gradebook/batch/view/(:any)','Administrator::viewBatch/$1');
    $routes->get('gradebook/batch/fetch','Administrator::fetchBatch');
    //inventory 
    $routes->match(['get','post'],'inventory','Administrator::inventory');
    $routes->get('inventory/stock/add','Administrator::addInventory');
    $routes->get('inventory/stock/export','Administrator::exportInventory');
    $routes->get('inventory/stock/edit/(:any)','Administrator::editInventory/$1');
    $routes->get('inventory/borrow','Administrator::borrowInventory');
    $routes->get('inventory/return','Administrator::returnInventory');
    $routes->get('inventory/report','Administrator::reportInventory');
    $routes->get('export/inventory','Export::exportInventory');
    //announcement
    $routes->match(['get','post'],'announcement','Administrator::announcement');
    $routes->get('announcement/create','Administrator::createAnnouncement');
    $routes->get('announcement/edit/(:any)','Administrator::editAnnouncement/$1');
    $routes->get('announcement/view/(:any)','Administrator::viewAnnouncement/$1');
    //reports
    $routes->get('reports','Administrator::report');
    $routes->get('reports/create','Administrator::createReport');
    $routes->get('reports/records','Administrator::allMerits');
    $routes->get('reports/review','Administrator::forReview');
    $routes->get('reports/edit/(:any)','Administrator::editReport/$1');
    $routes->get('export/merits-demerits','Export::exportMeritsDemerits');
    $routes->get('export/violations','Export::exportViolations');
    //maintenance
    $routes->get('maintenance/accounts','Administrator::accounts');
    $routes->get('maintenance/accounts/create','Administrator::createAccount');
    $routes->get('maintenance/accounts/edit/(:any)','Administrator::editAccount/$1');
    $routes->get('maintenance/recovery','Administrator::recovery');
    $routes->get('maintenance/settings','Administrator::settings');
    $routes->get('maintenance/permission/create','Administrator::createPermission');
    $routes->get('maintenance/permission/edit/(:any)','Administrator::editPermission/$1');
    //profile
    $routes->get('my-account','Administrator::myAccount');
});
$routes->group('',['filter'=>'AdminAlreadyLoggedIn'],function($routes)
{
    $routes->get('auth','Administrator::auth');
    $routes->get('reset-password', 'Administrator::resetPassword');
});